# coding: utf-8
root: /
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
title: Blog | Young
description: Too Young Too Simple
author: Thomas Young
email: 934619960@qq.com
category_list: true
links: true
address: http://www.thomasyoung.cn
url: http://www.thomasyoung.cn
gems: [jekyll-paginate]
theme: jekyll-theme-minimal
