# coding: utf-8
root: /
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
title: Blog | Young
description: Too Young Too Simple
author: Fantasy Shao
email: 934619960@qq.com
category_list: true
links: true
address: https://thomasyoung1989.github.io/blog/
url: https://thomasyoung1989.github.io/blog/
gems: [jekyll-paginate]
theme: jekyll-theme-minimal
